In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re
import joblib
import string

In [ ]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [ ]:
fake.head()

                                               title  ...               date
0   Donald Trump Sends Out Embarrassing New Year’...  ...  December 31, 2017
1   Drunk Bragging Trump Staffer Started Russian ...  ...  December 31, 2017
2   Sheriff David Clarke Becomes An Internet Joke...  ...  December 30, 2017
3   Trump Is So Obsessed He Even Has Obama’s Name...  ...  December 29, 2017
4   Pope Francis Just Called Out Donald Trump Dur...  ...  December 25, 2017

[5 rows x 4 columns]

In [ ]:
true.head()

                                               title  ...                date
0  As U.S. budget fight looms, Republicans flip t...  ...  December 31, 2017
1  U.S. military to accept transgender recruits o...  ...  December 29, 2017
2  Senior U.S. Republican senator: 'Let Mr. Muell...  ...  December 31, 2017
3  FBI Russia probe helped by Australian diplomat...  ...  December 30, 2017
4  Trump wants Postal Service to charge 'much mor...  ...  December 29, 2017

[5 rows x 4 columns]

In [ ]:
fake['class']=0
true['class']=1

In [ ]:
data = pd.concat([fake, true], axis = 0)

In [ ]:
data.sample(5)

                                                   title  ... class
2311   Kremlin agrees with Trump that bilateral ties ...  ...     1
16066  LAWYER SCAMS FEDS OUT OF $600 MILLION…Suddenly...  ...     0
8918   Zika sex research begins despite U.S. Congress...  ...     1
67      CNN BLISTERS Trump After He Attacks Them For ...  ...     0
7112    Comedian Margaret Cho Compares Donald Trump T...  ...     0

[5 rows x 5 columns]

In [ ]:
data = data.drop(["title", "subject", "date"], axis=1)

In [ ]:
data.reset_index(inplace=True)

In [ ]:
data.drop(['index'], axis=1, inplace=True)

In [ ]:
data.sample(5)

                                                    text  class
3797   A week after the election, much of the country...      0
3954   Fox Host Bret Baier found himself forced to re...      0
14618   If she doesn t wear a hijab, we hit her This ...      0
43061  MOSCOW (Reuters) - Russia is  extremely concer...      1
30356  BEIJING/GUATEMALA CITY (Reuters) - China calle...      1

In [ ]:
def text_clean(text):
  text = text.lower()
  text = re.sub('\[.*?\]', "", text)
  text = re.sub("\\W", "", text)
  text = re.sub("https?:://\S+|www\S+", "", text)
  text = re.sub("<.*?>+", "", text)
  text = re.sub("[%s]" % re.escape(string.punctuation),"", text)
  text = re.sub("\n", "", text)
  text = re.sub("\w*\d\w*", "", text)
  return text

In [ ]:
data["text"] = data["text"].apply(text_clean)

In [ ]:
x=data["text"]
y=data["class"]

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.25, random_state=42)

In [ ]:
vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(xtrain)
xv_test = vectorizer.transform(xtest)

In [ ]:
lr = LogisticRegression()
lr.fit(xv_train, ytrain)

LogisticRegression()

In [ ]:
prediction = lr.predict(xv_test)
lr.score(xv_test, ytest)

0.9860133630289533

In [ ]:
print(classification_report(ytest,prediction))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5895
           1       0.98      0.99      0.99      5330

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225

In [ ]:
joblib.dump(vectorizer, "vectorizer.jb")
joblib.dump(lr, "lr_model.jb")

['lr_model.jb']